CREATE TABLE IF NOT EXISTS STUDENTS_INVITATIONS (
    TOKEN BYTEA PRIMARY KEY,
    STUDENT_ID BIGINT NOT NULL,
    EXPIRY TIMESTAMP(
        0
    ) WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS ADMINS_INVITATIONS (
    TOKEN BYTEA PRIMARY KEY,
    ADMIN_ID BIGINT NOT NULL,
    EXPIRY TIMESTAMP(
        0
    ) WITH TIME ZONE NOT NULL
);