CREATE TABLE IF NOT EXISTS FOLLOWERS (
    USER_ID BIGINT NOT NULL,
    FOLLOWER_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    PRIMARY KEY(USER_ID, FOLLOWER_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (FOLLOWER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);