CREATE TABLE IF NOT EXISTS COMMENTS (
    ID BIGSERIAL PRIMARY KEY,
    POST_ID BIGSERIAL NOT NULL,
    USER_ID BIGSERIAL NOT NULL,
    CONTENT TEXT NOT NULL,
    CREATED_AT TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW()
);