CREATE EXTENSION IF NOT EXISTS CITEXT;

CREATE TABLE IF NOT EXISTS USERS (
    ID BIGSERIAL PRIMARY KEY,
    EMAIL CITEXT UNIQUE NOT NULL,
    USERNAME VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD BYTEA NOT NULL,
    BLOCKED BOOLEAN DEFAULT FALSE,
    FIRST_TIME_LOGIN BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION UPDATE_UPDATED_AT_COLUMN(
) RETURNS TRIGGER AS
    $$     BEGIN NEW.UPDATED_AT = NOW();
    RETURN NEW;
END;
$$     LANGUAGE PLPGSQL;
CREATE TRIGGER SET_UPDATED_AT BEFORE UPDATE ON USERS FOR EACH ROW EXECUTE

FUNCTION UPDATE_UPDATED_AT_COLUMN(
);