CREATE EXTENSION IF NOT EXISTS CITEXT;

CREATE TABLE IF NOT EXISTS POSTS (
    ID BIGSERIAL PRIMARY KEY,
    TITLE TEXT NOT NULL,
    CONTENT TEXT NOT NULL,
    USER_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION UPDATE_UPDATED_AT_COLUMN(
) RETURNS TRIGGER AS
    $$     BEGIN NEW.UPDATED_AT = NOW();
    RETURN NEW;
END;
$$     LANGUAGE PLPGSQL;
CREATE TRIGGER SET_UPDATED_AT BEFORE UPDATE ON POSTS FOR EACH ROW EXECUTE

FUNCTION UPDATE_UPDATED_AT_COLUMN(
);